### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kiankyars** [SeanOverton/SolanaNFTAssetPreparationScripts#1]
Why do you have the file made as append in createMetadata, because it should be write since we do not have the files before starting the program?

![Screen Shot 2022-02-03 at 11 06 27 AM](https://user-images.githubusercontent.com/69437137/152402502-a513dbac-373d-486a-b9e6-48eeb7132c22.png)

**Comment by SeanOverton** [comment]
Creates a new file anyway if their is not already files existing, but will make the change because if their was already files it would incorrectly append rather than overwrite.

**Comment by kiankyars** [comment]
Yes if you want to overwirite, you need to use 'w', not 'a'

**Comment by SeanOverton** [comment]
Yep agree, changed it
