### ISSUE TITLE
nftcreatorwithPercentages.py not working

### ISSUE THREAD

**Issue by joejoe168168** [SeanOverton/SolanaNFTAssetPreparationScripts#2]
It seems that the code is break with nftcreatorwithPercentages.py. When I run "python nftcreatorwithPercentages.py 100", it has the following error. (it seems can't find the key background, it should go ahead to look for the directory background)

also, it seems the repo doesn't have any NFTcreator.py as mentioned in README

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Projects\SolanaNFTAssetPreparationScripts\nftcreatorWithPercentages.py", line 202, in <module>
    main()
  File "Projects\SolanaNFTAssetPreparationScripts\nftcreatorWithPercentages.py", line 178, in main
    background = Image.open(choose_image_using_stats(TRAIT_ORDER[0]))
  File "Projects\SolanaNFTAssetPreparationScripts\nftcreatorWithPercentages.py", line 151, in choose_image_using_stats
    counts[name][image_choice] = 1
KeyError: 'Background'

**Comment by SeanOverton** [comment]
Yep so you will probably have to update the keys in in the "counts" dictionary. @joejoe168168

**Comment by SeanOverton** [comment]
There was a typo in the dict but I added the function add_to_counts() so that the counts dict no longer needs to be manually defined anyway.

**Comment by joejoe168168** [comment]
thanks, the script is working now
